# Generated by Django 5.1.3 on 2024-11-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dash",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Track", models.CharField(max_length=255)),
                ("Album_Name", models.CharField(max_length=100)),
                ("Artist", models.CharField(max_length=100)),
                ("Release_Date", models.DateField()),
                ("ISRC", models.CharField(max_length=100)),
                ("All_Time_Rank", models.IntegerField()),
                ("Track_Score", models.FloatField()),
                ("Spotify_Streams", models.FloatField()),
                ("Spotify_Playlist_Count", models.FloatField()),
                ("Spotify_Playlist_Reach", models.FloatField()),
                ("Spotify_Popularity", models.FloatField()),
                ("YouTube_Views", models.FloatField()),
                ("YouTube_Likes", models.FloatField()),
                ("YouTube_Playlist_Reach", models.FloatField()),
                ("TikTok_Posts", models.FloatField()),
                ("TikTok_Likes", models.FloatField()),
                ("TikTok_Views", models.FloatField()),
                ("Apple_Music_Playlist_Count", models.FloatField()),
                ("AirPlay_Spins", models.FloatField()),
                ("SiriusXM_Spins", models.FloatField()),
                ("Deezer_Playlist_Count", models.FloatField()),
                ("Deezer_Playlist_Reach", models.FloatField()),
                ("Amazon_Playlist_Count", models.FloatField()),
                ("Pandora_Streams", models.FloatField()),
                ("Pandora_Track_Stations", models.FloatField()),
                ("Soundcloud_Streams", models.FloatField()),
                ("Shazam_Counts", models.FloatField()),
                ("TIDAL_Popularity", models.FloatField()),
                ("Explicit_Track", models.IntegerField()),
            ],
        ),
    ]
